[book]
authors = ["BruceMaa"]
language = "en"
multilingual = false
src = "src"
title = "mdbook-template"
description = "The example book covers examples."

[build]
build-dir = "docs"
create-missing = true

[output.html]
default-theme = "light"
curly-quotes = true
mathjax-support = false
google-analytics = "UA-82993633-1"
no-section-label = false
git-repository-url = "https://github.com/GitHubTemplates/docs-use-mdbook"
git-repository-icon = "fa-github"

[output.html.playpen]
editable = false
copy-js = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true